// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProfileService.DataAccess;

#nullable disable

namespace ProfileService.DataAccess.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20230411022345_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProfileService.BusinessLogic.Entities.Bonus", b =>
                {
                    b.Property<Guid>("BonusId")
                        .HasColumnType("uuid")
                        .HasColumnName("bonus_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer")
                        .HasColumnName("discount_type");

                    b.Property<bool>("IsAlreadyUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_already_used");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("BonusId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Bonuses", (string)null);
                });

            modelBuilder.Entity("ProfileService.BusinessLogic.Entities.ProfileData", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("ProfileId");

                    b.ToTable("ProfileDatas", (string)null);
                });

            modelBuilder.Entity("ProfileService.BusinessLogic.Entities.Bonus", b =>
                {
                    b.HasOne("ProfileService.BusinessLogic.Entities.ProfileData", "ProfileData")
                        .WithMany("Bonuses")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfileData");
                });

            modelBuilder.Entity("ProfileService.BusinessLogic.Entities.ProfileData", b =>
                {
                    b.Navigation("Bonuses");
                });
#pragma warning restore 612, 618
        }
    }
}
