// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProfileService.DataAccess.EF;

#nullable disable

namespace ProfileService.DataAccess.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20230126122857_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProfileService.BusinessLogic.Bonus", b =>
                {
                    b.Property<Guid>("BonusId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("isAlreadyUsed")
                        .HasColumnType("boolean");

                    b.HasKey("BonusId");

                    b.HasIndex("PersonalId");

                    b.ToTable("Bonus", (string)null);
                });

            modelBuilder.Entity("ProfileService.BusinessLogic.PersonalData", b =>
                {
                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonalId");

                    b.ToTable("PersonalData", (string)null);
                });

            modelBuilder.Entity("ProfileService.BusinessLogic.Bonus", b =>
                {
                    b.HasOne("ProfileService.BusinessLogic.PersonalData", "PersonalData")
                        .WithMany("Bonuses")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalData");
                });

            modelBuilder.Entity("ProfileService.BusinessLogic.PersonalData", b =>
                {
                    b.Navigation("Bonuses");
                });
#pragma warning restore 612, 618
        }
    }
}
